name: Configuration Check
on:
  repository_dispatch:
    types:
      - configuration-check
      - config
  workflow_dispatch:
jobs:
  check:
    name: Run check
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: 'echo "${{ github.event.client_payload.app }}"'
      - run: 'echo "payload: ${{ toJson(github.event.client_payload) }}"'
      - run: |
          echo '$X' > hi.txt
          envsubst < hi.txt
          cat hi.txt
        env:
          X: "hello world"
