name: Configuration Check
on:
  repository_dispatch:
    types:
      - configuration-check
      - config
jobs:
  check:
    name: Run check
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo ${{ github.event.client_payload }}
      - name: Say hello2
        run: echo ${{ github.event.client_payload.app }}
